alter table AbstractNode drop foreign key FKDCA185641A30934D;
alter table AbstractNode drop foreign key FKDCA18564DAB1BD9F;
alter table AbstractNode drop foreign key FKDCA185642ECE35D1;
alter table Chat drop foreign key FK200778BC72EAFC;
alter table ChatEntry drop foreign key FKD691FBDA6360975C;
alter table USER_ROLE drop foreign key FKBC16F46A896B1A9C;
alter table USER_ROLE drop foreign key FKBC16F46A2E95DE7C;
drop table if exists AbstractNode;
drop table if exists BaseAction;
drop table if exists Chat;
drop table if exists ChatEntry;
drop table if exists ErrorLog;
drop table if exists Role;
drop table if exists Server;
drop table if exists TPF_USER;
drop table if exists USER_ROLE;
create table AbstractNode (DTYPE varchar(31) not null, id bigint not null auto_increment, answer varchar(255), description varchar(255), keywords varchar(255), action_id bigint, errorTransition_id bigint, parent_id bigint, primary key (id), unique (description));
create table BaseAction (DTYPE varchar(31) not null, id bigint not null auto_increment, version bigint, description varchar(255), methodNane varchar(255), serviceName varchar(255), wsdlUrl varchar(255), primary key (id), unique (description));
create table Chat (id bigint not null auto_increment, version bigint, chat_client varchar(255), finalNode varchar(255), chat_length integer, is_successful bit, server_id bigint, primary key (id));
create table ChatEntry (id bigint not null auto_increment, version bigint, cdate datetime, message varchar(255), userQuery bit not null, chat_id bigint, primary key (id));
create table ErrorLog (id bigint not null auto_increment, version bigint, message longtext, stackTrace longtext, timestamp datetime, primary key (id));
create table Role (id bigint not null auto_increment, version bigint, roleDescription varchar(255), roleName varchar(255), primary key (id));
create table Server (id bigint not null auto_increment, version bigint, enabled bit not null, hostname varchar(255), maxChatterbots integer not null, maxLoad float not null, name varchar(255), port integer not null, primary key (id), unique (hostname, port));
create table TPF_USER (id bigint not null auto_increment, version bigint, email varchar(255), firstName varchar(255), lastName varchar(255), password varchar(255), username varchar(255), primary key (id));
create table USER_ROLE (USER_ID bigint not null, ROLE_ID bigint not null);
alter table AbstractNode add index FKDCA185641A30934D (action_id), add constraint FKDCA185641A30934D foreign key (action_id) references BaseAction (id);
alter table AbstractNode add index FKDCA18564DAB1BD9F (errorTransition_id), add constraint FKDCA18564DAB1BD9F foreign key (errorTransition_id) references AbstractNode (id);
alter table AbstractNode add index FKDCA185642ECE35D1 (parent_id), add constraint FKDCA185642ECE35D1 foreign key (parent_id) references AbstractNode (id);
alter table Chat add index FK200778BC72EAFC (server_id), add constraint FK200778BC72EAFC foreign key (server_id) references Server (id);
alter table ChatEntry add index FKD691FBDA6360975C (chat_id), add constraint FKD691FBDA6360975C foreign key (chat_id) references Chat (id);
alter table USER_ROLE add index FKBC16F46A896B1A9C (ROLE_ID), add constraint FKBC16F46A896B1A9C foreign key (ROLE_ID) references Role (id);
alter table USER_ROLE add index FKBC16F46A2E95DE7C (USER_ID), add constraint FKBC16F46A2E95DE7C foreign key (USER_ID) references TPF_USER (id);
